RSpec.describe(MB::Sound::MIDI::ControlMap) do
  let(:spec_class) { MB::Sound::MIDI::ControlSpec }

  # The controls of spec/test_data/acid_xml_reference.xml, written by the old
  # MIDI::Manager#to_acid_xml (on_cc 1, 7, and 20, then a CC 64 threshold).
  let(:reference_specs) {
    [
      spec_class.new(number: 1, name: 'Modulation'),
      spec_class.new(number: 7, name: 'Volume', default: 100),
      spec_class.new(number: 20, name: 'Cutoff', range: 0.0..2.0, center: 1.0, default: 64),
      spec_class.new(number: 64, name: 'Sustain', curve: :switch),
    ]
  }

  # The same controls set up on the old MIDI::Manager.
  def old_manager
    m = MB::Sound::MIDI::Manager.new(input: Object.new, channel: nil)
    m.on_cc(1, range: 0.0..1.0, description: 'Modulation') {}
    m.on_cc(7, range: 0.0..1.0, default: 100 / 127.0, description: 'Volume') {}
    m.on_cc(20, range: 0.0..2.0, default: 1.0, description: 'Cutoff') {}
    m.on_cc_threshold(64, 64, 64, description: 'Sustain') {}
    m
  end

  def synth(**opts)
    MB::Sound::Synth.new('spec/test_data/c_major.mid', voices: 2, **opts) { |v|
      v.hz.vibrato.saw.filter(:lowpass, cutoff: v.cutoff(400), quality: 1) * v.amp_env + v.cc(20, name: 'X') * 0
    }
  end

  describe '#to_acid_xml' do
    it 'matches the XML of the old MIDI::Manager byte for byte' do
      xml = described_class.new(reference_specs).to_acid_xml(name: 'test_synth')
      expect(xml).to eq(File.read('spec/test_data/acid_xml_reference.xml'))
    end

    it 'matches XML generated by the old code while it still exists' do
      skip 'The old MIDI::Manager is gone' unless defined?(MB::Sound::MIDI::Manager)

      old = old_manager.to_acid_xml(name: 'test_synth')
      expect(described_class.new(reference_specs.shuffle).to_acid_xml(name: 'test_synth')).to eq(old)
      expect(old).to eq(File.read('spec/test_data/acid_xml_reference.xml'))
    end

    it 'joins the names of specs on one controller into one entry, like the old code, counting entries' do
      specs = [spec_class.new(number: 1, name: 'Modulation'), spec_class.new(number: 1, name: 'hz', range: 0.0..6.0, center: 3.0, default: 64)]
      xml = described_class.new(specs).to_acid_xml(name: 'x')
      expect(xml.scan('<param ').length).to eq(1)
      expect(xml).to include('<param name="Modulation, hz">', '<Neutral>0</Neutral>', 'params="1"')

      if defined?(MB::Sound::MIDI::Manager)
        m = MB::Sound::MIDI::Manager.new(input: Object.new, channel: nil)
        m.on_cc(1, range: 0.0..1.0, description: 'Modulation') {}
        m.on_cc(1, range: 0.0..6.0, default: 3.0, description: 'hz') {}

        # The old code counted every parameter instead of every entry
        expect(m.to_acid_xml(name: 'x').sub('params="2"', 'params="1"')).to eq(xml)
      end
    end

    it 'writes a continuous entry when a controller has both switch and continuous specs' do
      specs = [spec_class.new(number: 64, name: 'Sustain', curve: :switch), spec_class.new(number: 64, name: 'Wet', default: 10)]
      xml = described_class.new(specs).to_acid_xml(name: 'x')
      expect(xml).to include('<param name="Sustain, Wet">', '<CurveType>LINEAR</CurveType>', '<Neutral>10</Neutral>')
      expect(xml).not_to include('SWITCH')
    end

    it 'escapes names' do
      xml = described_class.new(spec_class.new(number: 3, name: 'A & <B> "C"')).to_acid_xml(name: 'x&y')
      expect(xml).to include('mapname="x&amp;y"', 'name="A &amp; &lt;B&gt; &quot;C&quot;"')
    end

    it 'is named after the script by default' do
      expect(described_class.new.to_acid_xml).to include(%Q{mapname="#{File.basename($0)}"}, 'params="0"')
    end
  end

  describe 'pitch bend and channel pressure' do
    # The controls of spec/test_data/acid_xml_bend_reference.xml, written by
    # the old MIDI::Manager#to_acid_xml (at 2e20764^, before the old layer
    # was deleted) with on_cc(1, description: 'Modulation'), on_cc(74,
    # range: 0.0..2.0, default: 1.0, description: 'Brightness'),
    # on_midi(MIDIMessage::ChannelAftertouch.new(nil, 0)), and
    # on_bend(range: -2.0..2.0, default: 0.0), the old MidiDsl#bend's call.
    let(:bend_specs) {
      [
        spec_class.bend(range: -2.0..2.0),
        spec_class.new(number: 74, name: 'Brightness', range: 0.0..2.0, center: 1.0, default: 64),
        spec_class.pressure,
        spec_class.new(number: 1, name: 'Modulation'),
      ]
    }

    it 'writes them after the CCs as the old code did, byte for byte' do
      xml = described_class.new(bend_specs).to_acid_xml(name: 'test_synth')
      expect(xml).to eq(File.read('spec/test_data/acid_xml_bend_reference.xml'))
    end

    it 'sorts them after the CCs, pressure first, grouping specs of one kind' do
      bend2 = spec_class.bend
      map = described_class.new(*bend_specs, bend2)
      expect(map.map(&:name)).to eq(['Modulation', 'Brightness', 'Aftertouch', 'Pitch Bend', 'Pitch Bend'])
      expect(map.numbers).to eq([1, 74])
      expect(map.types).to eq([:cc, :pressure, :bend])
      expect(map[:bend]).to eq([bend_specs[0], bend2])
      expect(map[:pressure]).to eq([bend_specs[2]])
      expect(map.groups.keys).to eq([1, 74, :pressure, :bend])
      expect(map.to_acid_xml(name: 'x').scan('<param ').length).to eq(4)
      expect(map.to_s).to include("\n  Aftertouch (0.0..1.0, default 0) - Channel pressure\n  Pitch Bend (-2.0..2.0, default 8192) - Pitch bend\n")
      expect(map.inspect).to end_with('CC 74 Brightness, Aftertouch, Pitch Bend, Pitch Bend>')
    end

    it 'finds them on a Notes and in a Synth (the bend inside v.hz)' do
      notes = MB::Sound::Notes.new('spec/test_data/c_major.mid')
      b = notes.bend
      pr = notes.pressure
      expect(notes.controls.map(&:type)).to eq([:pressure, :bend])
      expect(notes.controls[:bend].first.range).to eq(-1.0..1.0)

      s = synth
      expect(s.controls.types).to eq([:cc, :bend])
      expect(s.controls[:bend].map(&:range)).to eq([-2.0..2.0])
      expect(s.controls.to_acid_xml(name: 'x')).to include('<MIDIMsg>224</MIDIMsg>')

      s = MB::Sound::Synth.new('spec/test_data/c_major.mid', voices: 1) { |v| v.hz.bend_range(12.st).saw * v.pressure }
      expect(s.controls.types).to eq([:cc, :pressure, :bend]) # pedals, then pressure and bend
      expect(s.controls[:bend].map(&:range)).to eq([-12.0..12.0])
      expect([b, pr]).to all(respond_to(:control_specs))
    end
  end

  describe '#write_acid_xml' do
    it 'writes the XML to a file' do
      path = tmp_path('map.xml')
      map = described_class.new(reference_specs)
      expect(map.write_acid_xml(path, name: 'test_synth')).to eq(path)
      expect(File.read(path)).to eq(File.read('spec/test_data/acid_xml_reference.xml'))
    end
  end

  describe 'collecting controls' do
    it 'keeps equal specs once and sorts by controller number, keeping the order added on each' do
      a = spec_class.new(number: 20, name: 'A')
      b = spec_class.new(number: 1, name: 'B')
      c = spec_class.new(number: 20, name: 'C')
      map = described_class.new(a, [b, spec_class.new(number: 20, name: 'A')], described_class.new(c, b))
      expect(map.to_a).to eq([b, a, c])
      expect(map.size).to eq(3)
      expect(map.numbers).to eq([1, 20])
      expect(map[20]).to eq([a, c])
      expect(map[2]).to eq([])
      expect(map.groups).to eq({ 1 => [b], 20 => [a, c] })
      expect(map.add(nil)).to equal(map)
      expect(map).to eq(described_class.new(b, a, c))
    end

    it 'collects the controller nodes in use on a Notes' do
      notes = MB::Sound::Notes.new('spec/test_data/c_major.mid')
      mod = notes.mod
      cc = notes.cc(20, name: 'X')
      map = notes.controls
      expect(map).to be_a(described_class)
      expect(map.map(&:number)).to eq([1, 20])
      expect([mod, cc]).to all(be_a(MB::Sound::Notes::Control))
    end

    it "collects a Synth's lane controllers, output controls, and sustain pedals" do
      s = synth(controls: [:volume, :pan])
      numbers = s.controls.numbers
      expect(numbers).to include(1, 7, 10, 20, 64, 66, 67, 74, 76, 77, 78)
      expect(s.controls.find { |c| c.number == 64 }).to have_attributes(name: 'Sustain', curve: :switch)
      expect(s.output_controls).to eq([:volume, :pan])
    end

    it 'leaves out the pedals of a Synth without sustain' do
      expect(synth(sustain: false).controls.numbers).not_to include(64, 66, 67)
    end

    it 'finds controller nodes and synths in a graph or bundle' do
      notes = MB::Sound::Notes.new('spec/test_data/c_major.mid')
      s = synth(controls: [:pan])
      graph = s.outputs.map { |o| o * notes.cc(30, name: 'Gain') }
      map = described_class.new(MB::Sound::GraphNode::Channels.new(graph))
      expect(map.numbers).to include(10, 20, 30, 64)
      expect(described_class.new(graph).to_a).to eq(map.to_a)
    end

    it 'merges controllers of the same number from different streams' do
      notes = MB::Sound::Notes.new('spec/test_data/c_major.mid')
      hz = notes.cc(1, name: 'hz', range: 0.0..6.0)
      s = synth
      map = described_class.new(s, notes)
      expect(map[1].map(&:name)).to eq(['Modulation', 'hz'])
      expect(map.to_acid_xml(name: 'x')).to include('<param name="Modulation, hz">')
      expect(hz.spec.number).to eq(1)
    end

    it 'raises for objects without controls' do
      expect { described_class.new(Object.new) }.to raise_error(ArgumentError, /MIDI controls/)
    end
  end

  describe 'text' do
    let(:map) { described_class.new(reference_specs) }

    it 'lists one line per spec with descriptions' do
      map.add(spec_class.new(number: 2, name: 'Breath', description: 'Blow'))
      expect(map.to_s.lines.map(&:rstrip)).to eq([
        'MIDI controls:',
        '  CC   1 Modulation (0.0..1.0, default 0)',
        '  CC   2 Breath (0.0..1.0, default 0) - Blow',
        '  CC   7 Volume (0.0..1.0, default 100)',
        '  CC  20 Cutoff (0.0..2.0, default 64)',
        '  CC  64 Sustain (0.0..1.0, switch, default 0)',
      ])
    end

    it 'says when there are none' do
      expect(described_class.new.to_s).to eq('MIDI controls: none')
    end

    it 'shows the listing in pp (and Pry) and a summary in #inspect' do
      expect(map.pretty_inspect).to eq("#{map}\n")
      expect(map.inspect).to eq('#<MB::Sound::MIDI::ControlMap CC 1 Modulation, CC 7 Volume, CC 20 Cutoff, CC 64 Sustain>')
    end
  end
end
